version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "12:00"
      timezone: "America/New_York"
    versioning-strategy: increase
    open-pull-requests-limit: 20
    insecure-external-code-execution: deny
    allow:
      - dependency-type: "all"
  